# Generated by Django 5.0.1 on 2024-02-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrustType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.crusttype')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizzacheese')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizzasauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizzasize')),
                ('toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizzatoppings')),
            ],
        ),
    ]
