# Generated by Django 5.0.1 on 2024-02-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_crusttype_pizzacheese_pizzasauce_pizzasize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
