# Generated by Django 5.0.1 on 2024-02-20 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_remove_pizza_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('card_number', models.BigIntegerField()),
                ('expire_month', models.IntegerField()),
                ('expire_year', models.IntegerField()),
                ('ccv', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('eta', models.DateTimeField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
